name: inject-plugin-demo
main: cc.wanforme.nukkit.insp.InjectNSPlugin
version: "1.0.0"
api: ["1.0.0"]
load: POSTWORLD
author: Nukkit Project
authors: ["wanne"]

commands:
  test2:
    description: Test2 command
    usage: "/test2"
    aliases: []
    permission: exampleplugin.command.example
    permission-message: "You do not have the required permission to run /example"
permissions:
  exampleplugin.command.example:
    description: "Allows the user to run the example command"
    default: true
